TotalAttendees: Total attendees
TotalEventsForThisMonth: Total events for this month
NoEventsYet: There are no events yet
NoAttendeesForThisEventYet: There are no participants for this event yet
List: List
RegistrationDate: Date of registration
IssueDate: Issue date
NoCardsRegisteredYet: No cards have been registered yet
EventsCatalogue: Events catalogue
SearchEvents: Search for events
SelectAnEventToRegisterPlease: Please select an event to register
NoUpcomingEventsYet: There are no upcoming events yet
TotalEventsForThisMonthN n@Int: Total events for this month: #{show n}
NoEventsForThisMonth: There are currently no events for this month
QrCode: Qr Code
Attendee: Attendee
Attendees: Attendees
Subscribers: Subscribers
UserSuccessfullyegisteredForEvent: User has successfully registered for the event
ScanAgain: Scan again
ConfirmUserRegistrationForEventPlease: Please confirm user registration for the event
Registration: Registration
NoEventsForThisDayYet: There are no events for this day yet
Register: Register
RegisterUserForEvent: Register user for event
RegistrationConfirmation: Registration confirmation
RegistrationForEvent: Registration for the event
Scan: Scan
Card: Card
Cards: Cards
UserCard: User card
UserCards: User cards
PersonalUserCard: Personal user card
PersonalUserCards: Personal user cards
UpcomingEvents: Upcoming events
ScanQrCode: Scan QR code
ScanQrCodeAndLinkToEvent: Scan the visitor's QR code and link it to the event
EventsCalendar: Events calendar
Time: Time
Events: Events
Event: Event
Next: Next
Previous: Previous
Sun: Sun
Sat: Sat
Fri: Fri
Thu: Thu
Wed: Wed
Tue: Tue
Mon: Mon
Calendar: Calendar
Stop: Stop
PointYourCameraToScan: Point your camera at the QR code to scan
Scanner: Scanner

IssueTracking: Issue tracking
Timeout: Timeout
Find: Find
Radius: Radius
MainMenu: Main menu
Type: Type
Brand: Brand
Phone: Phone
OpeningHours: Opening hours
Address: Address
Search: Search
Landmark: Landmark
Close: Close
Tooltip: Tooltip
Duration: Duration
EndDate: End date
StartDate: Start date
Chart: Chart
Action: Action
Timestamp: Timestamp
Hours: Hours
DurationHours: Duration
Remarks: Remarks
StateMachineDiagram: State machine diagram
BasicEntities: Basic entities
NotAuthorized: Not authorized
LoginToAccessPlease: Please login to access this page
Statistics: Statistics
Owner: Owner
Sequence: Sequence
End: End
Start: Start
LoginForMoreDetailsPlease: Please login for more details
WelcomeTo: Welcome to
Location: Location
ChangePassword: Change password
AlreadyExists: Already exists
No: No
Yes: Yes
DemoUserAccounts: Demo user accounts
User: User
Administrator: Administrator
InvalidUrlOrRemoved: Invalid URL or resource removed
Authentication: Authentication
Or: or
Back: Back
BackToHomepage: Go back to homepage
InvalidArguments: Invalid arguments
PermissionDenied: Permission denied
PageNotFound: Page not found
PleaseAddIfNecessary: Please add if necessary
Empty: Empty
Copy: Copy
Settings: Settings
Country: Country
CountryRU: RU
CountryUS: US
Language: Language
LangRu: Russian
LangEn: English
Create: Create
Link: Link
Attribution: Attribution
Logo: Logo
Photo: Photo
Url: URL
Details: Details
Title: Title
RecordDeleted: Record deleted
InvalidFormData: Invalid form data
DateCreated: Date created
TimeCreated: Time created
Author: Author
SourceCode: Source code
GitHub: GitHub
EntityRelationshipDiagram: Entity relationship diagram
Documentation: Documentation
Description: Description
Name: Name
RecordEdited: Record edited
RecordAdded: Record added
Edit: Edit
DeleteAreYouSure: Are you sure you want to delete?
ConfirmPlease: Please confirm
Actions: Actions
Homepage: Home page
MenuButton: Menu button
Save: Save
Cancel: Cancel
Dele: Delete
Change: Change
Add: Add
NoData: No data
NothingToShow: Nothing to show
EmptyDataSet: Empty dataset
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in to access this page
Users: Users
Email: E-mail
ResetPassword: Reset password
RestoreLogin: Restore login
Password: Password
Username: Username
SignOut: Sign out
SignIn: Sign in
Home: Home
AppName: EventQr

Doc001 appname@Text href@Text: The web application <a class="link" href=#{href} target=_blank>#{appname}</a> registers users for events.
Doc002 href@Text: <a class="link" href=#{href} target=_blank>Project repository</a> on GitHub.
Doc003 href@Text: Please note that the application currently running is a demo application. Any actions are allowed and encouraged. <a class="link" href=#{href} target=_blank>Report issues</a> on GitHub.
Doc005: Integration with external APIs