ProjectId: Project ID
ClientSecret: Client secret
ClientId: Client id
Superuser: Superuser
SelectLocationToStoreRefreshToken: Select a location to store the refresh token
UserAccountThroughWhichMailWillBeSent: User account through which mail will be sent
UnknownMessageRecipient: Unknown message recipient
UnknownMessagePublisher: Unidentified message publisher
UnknownAccountForSendingEmail: Unknown account for sending email
RefreshTokenIsNotInitialized: The refresh token is not initialized
UnableToObtainAccessToken: Unable to obtain access token
Vapid: VAPID
Gmail: Gmail
InvalidGoogleAPITokens: Invalid Google API tokens
VapidGenerationWarning: Generating a new VAPID key will require all clients to re-subscribe to push notifications
Generate: Generate
GoogleSecretManager: Google Secret Manager
GmailAccount: Gmail account
Cleared: Cleared
ClearSettings: Clear
InvalidStoreType: Invalid store type
StoreType: Store type
Database: Database
UserSession: User session
Initialize: Initialize
Tokens: Tokens
NotificationSent: Notification sent
UploadPoster: Upload poster
Poster: Poster
Overview: Overview
UseCaseDiagram: Use Case Diagram
ReadMessage: Read
DismissNotification: Dismiss
EnableCameraPlease: Please enable the camera in your browser settings
CameraWasTurnedOff: It looks like the camera was turned off
EnableNotificationsPlease: Please enable notifications in your browser settings
NotificationsHaveBeenDisabled: It looks like notifications have been disabled
UnsubscribeSuccessful: Unsubscribe was successful
SubscriptionSuccessful: Subscription successful
VapidNotInitializedProperly: VAPID was not initialized properly
SubscribeToPushNotifications: Subscribe to push notifications
AnotherAccountAccessProhibited: Access to another user's account is prohibited
ItLooksLikeUserNotSubscribedToPushNotifications: It looks like the user is not subscribed to push notifications
ItLooksLikeUserNotSubscribed: It looks like the user is not subscribed
SendPushNotification: Send push notification
NotificationSentToSubscribersN n@Int: Notification sent to #{show n} subscribers
EmailAddress: Email address
Message: Message
MessageSubject: Subject
Header: Header
SendEmail: Send Email
NotificationToAttendee: Notification to attendee
SendNotification: Send notification
Send: Send
ShowUserQrCode: Show user QR code
NotifyUser: Notify user
NotifyUserAboutUpcomingEvent: Notify user about upcoming event
NoEventsFound: No events found
NumberOfAttendees: Number of attendees
UserHasNoCardsYet: The user has no cards yet
NoFieldsForThisCardYet: There are no fields for this card yet
NewFieldNameRequired: The name of the new field must be specified
Value: Value
Cardholder: Cardholder
CardNumber: Card number
NewField: New field
AddField: Add field
TotalAttendees: Total attendees
TotalEventsForThisMonth: Total events for this month
NoEventsYet: There are no events yet
NoAttendeesForThisEventYet: There are no participants for this event yet
List: List
RegistrationDate: Date of registration
IssueDate: Issue date
NoCardsRegisteredYet: No cards have been registered yet
EventsCatalogue: Events catalogue
SearchEvents: Search for events
SelectAnEventToRegisterPlease: Please select an event to register
NoUpcomingEventsYet: There are no upcoming events yet
TotalEventsForThisMonthN n@Int: Total events for this month: #{show n}
NoEventsForThisMonth: There are currently no events for this month
QrCode: Qr Code
Attendee: Attendee
Attendees: Attendees
Subscribers: Subscribers
UserSuccessfullyRegisteredForEvent: User successfully registered for the event
ScanAgain: Scan again
ConfirmUserRegistrationForEventPlease: Please confirm user registration for the event
Registration: Registration
NoEventsForThisDayYet: There are no events for this day yet
Register: Register
RegisterUserForEvent: Register user for event
RegistrationConfirmation: Registration confirmation
RegistrationForEvent: Registration for the event
Scan: Scan
Card: Card
Cards: Cards
UserCard: User card
UserCards: User cards
PersonalUserCard: Personal user card
PersonalUserCards: Personal user cards
UpcomingEvents: Upcoming events
ScanQrCode: Scan QR code
ScanQrCodeAndLinkToEvent: Scan the visitor's QR code and link it to the event
ScanQrCodeAndLinkToThisEvent: Scan the visitor's QR code and link it to this event
EventsCalendar: Events calendar
Time: Time
Events: Events
Event: Event
Next: Next
Previous: Previous
Sun: Sun
Sat: Sat
Fri: Fri
Thu: Thu
Wed: Wed
Tue: Tue
Mon: Mon
Calendar: Calendar
Stop: Stop
PointYourCameraToScan: Point your camera at the QR code to scan
Scanner: Scanner

IssueTracking: Issue tracking
Timeout: Timeout
Find: Find
Radius: Radius
MainMenu: Main menu
Type: Type
Brand: Brand
Phone: Phone
OpeningHours: Opening hours
Address: Address
Search: Search
Landmark: Landmark
Close: Close
Tooltip: Tooltip
Duration: Duration
EndDate: End date
StartDate: Start date
Chart: Chart
Action: Action
Timestamp: Timestamp
Hours: Hours
DurationHours: Duration
Remarks: Remarks
StateMachineDiagram: State machine diagram
BasicEntities: Basic entities
NotAuthorized: Not authorized
SignInToAccessPlease: Please sign in to access this page
LoginToAccessPlease: Please login to access this page
Statistics: Statistics
Owner: Owner
Sequence: Sequence
End: End
Start: Start
LoginForMoreDetailsPlease: Please login for more details
WelcomeTo: Welcome to
Location: Location
ChangePassword: Change password
AlreadyExists: Already exists
No: No
Yes: Yes
DemoUserAccounts: Demo user accounts
User: User
Administrator: Administrator
InvalidUrlOrRemoved: Invalid URL or resource removed
Authentication: Authentication
Or: or
Back: Back
BackToHomepage: Go back to homepage
InvalidArguments: Invalid arguments
PermissionDenied: Permission denied
PageNotFound: Page not found
PleaseAddIfNecessary: Please add if necessary
Empty: Empty
Copy: Copy
Settings: Settings
Country: Country
CountryRU: RU
CountryUS: US
Language: Language
LangRu: Russian
LangEn: English
Create: Create
Link: Link
Attribution: Attribution
Logo: Logo
Photo: Photo
Url: URL
Details: Details
Title: Title
RecordDeleted: Record deleted
InvalidFormData: Invalid form data
DateCreated: Date created
TimeCreated: Time created
Author: Author
SourceCode: Source code
GitHub: GitHub
EntityRelationshipDiagram: Entity relationship diagram
Documentation: Documentation
Description: Description
Name: Name
RecordEdited: Record edited
RecordAdded: Record added
Edit: Edit
DeleteAreYouSure: Are you sure you want to delete?
ConfirmPlease: Please confirm
Actions: Actions
Homepage: Home page
MenuButton: Menu button
Save: Save
Cancel: Cancel
Dele: Delete
Change: Change
Add: Add
NoData: No data
NothingToShow: Nothing to show
EmptyDataSet: Empty dataset
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in
Users: Users
Email: E-mail
ResetPassword: Reset password
RestoreLogin: Restore login
Password: Password
Username: Username
SignOut: Sign out
SignIn: Sign in
Home: Home
AppName: EventQr

Doc000: Event and Attendance Management
Doc001 appname@Text href@Text: <a class="link" href=#{href} target=_blank>#{appname}</a> allows managers to register events, notify users about upcoming events and track attendance.
Doc002 href@Text: <a class="link" href=#{href} target=_blank>Project repository</a> on GitHub.
Doc003 href@Text: Please note that the application currently running is a demo application. Any actions are allowed and encouraged. <a class="link" href=#{href} target=_blank>Report issues</a> on GitHub.
Doc004: A superuser account is defined at deployment time. The superuser manages other users and grants or revokes administrator privileges to specific users.
Doc005: Integration with external APIs