IssueTracking: Issue tracking
GeolocationAlternativesMessageCoordinates: coordinates
GeolocationAlternativesMessageOrThe: or the
GeolocationAlternativesMessageAddress: address
GeolocationAlternativesMessageSuffix: of your location
GeolocationAlternativesMessagePrefix: Alternatively, you can specify an
GeolocationStatusTimeoutUserMessage: The timeout for determining your location has expired.
GeolocationStatusUserMessage: Your location is determined using the browser's geolocation capabilities.
GeolocationNotSupportedUserMessage: It looks like your browser does not support geolocation.
GeolocationStatusDisabledExploreNearby: It looks like you have geolocation disabled, for it is needed to explore nearby objects. Please enable geolocation for this site in your browser settings.
GeolocationStatusDisabledUserMessage: It looks like you have geolocation disabled, for it is needed to map your location. Please enable geolocation for this site in your browser settings.
AboutYourLocation: About your location
GeolocationOptions: Geolocation options
Geolocation: Geolocation
Latitude: Latitude
Longitude: Longitude
GeolocationDisabled: Geolocation is disabled
Timeout: Timeout
PositionUnavailable: Position unavailable
Find: Find
PublicInstitutions: Public institutions
Parks: Parks
Nearby: Nearby
InKilometers: in kilometers
NearbyRadius: Radius close to my location
Radius: Radius
MainMenu: Main menu
RestaurantsShopsAndMore: Restaurants, shops and more
Attractions: Attractions
MapStyleOptions: Map style options
Compass: Compass
MyLocation: My location
ZoomOut: Zoom out
ZoomIn: Zoom in
ExploreNearby: Explore nearby
NoShops: There are no shops
NoShopsWereFoundForSearchTerms: No shops were found containing all your search terms
NoRestaurants: There are no restaurants
NoRestaurantsWereFoundForSearchTerms: No restaurants were found containing all your search terms
ThatIsAll: That's all
LoadMore: Load more
Type: Type
Brand: Brand
ShowOnMap: Show on map
Phone: Phone
OpeningHours: Opening hours
Address: Address
Cuisine: Cuisine
Restaurant: Restaurant
SearchForShops: Search for shops
SearchForRestaurants: Search for restaurants
SearchByNameOrAddress: Search by name or address
SearchPlacesByNameOrAddress: Search for places by name or address
SearchPlacesByName: Search places by name
SearchByStreetNamesAndPoi: Search by street names and places of interest
NoLocationsWereFound: No locations were found matching your search
Shops: Shops
Restaurants: Restaurants
Search: Search
StyleNavigationNight: Navigation night
StyleNavigationDay: Navigation day
StyleSatelliteStreets: Satellite streets
StyleSatellite: Satellite
StyleDark: Dark
StyleLight: Light
StyleOutdoors: Outdoors
StyleStreets: Streets
CouldNotGetPosition: Could not get position
Landmark: Landmark
Close: Close
Tooltip: Tooltip
Duration: Duration
EndDate: End date
StartDate: Start date
Chart: Chart
Action: Action
Timestamp: Timestamp
Hours: Hours
DurationHours: Duration
Remarks: Remarks
StateMachineDiagram: State machine diagram
BasicEntities: Basic entities
NotAuthorized: Not authorized
LoginToAccessPlease: Please login to access this page
Statistics: Statistics
Owner: Owner
Sequence: Sequence
End: End
Start: Start
LoginForMoreDetailsPlease: Please login for more details
WelcomeTo: Welcome to
Location: Location
ChangePassword: Change password
AlreadyExists: Already exists
No: No
Yes: Yes
DemoUserAccounts: Demo user accounts
User: User
Administrator: Administrator
InvalidUrlOrRemoved: Invalid URL or resource removed
Authentication: Authentication
Or: or
Back: Back
BackToHomepage: Go back to homepage
InvalidArguments: Invalid arguments
PermissionDenied: Permission denied
PageNotFound: Page not found
PleaseAddIfNecessary: Please add if necessary
Empty: Empty
Copy: Copy
Settings: Settings
Country: Country
CountryRU: RU
CountryUS: US
Language: Language
LangRu: Russian
LangEn: English
Create: Create
Link: Link
Attribution: Attribution
Logo: Logo
Photo: Photo
Url: URL
Details: Details
Title: Title
RecordDeleted: Record deleted
InvalidFormData: Invalid form data
DateCreated: Date created
TimeCreated: Time created
Author: Author
SourceCode: Source code
GitHub: GitHub
EntityRelationshipDiagram: Entity relationship diagram
Documentation: Documentation
Description: Description
Name: Name
RecordEdited: Record edited
RecordAdded: Record added
Edit: Edit
DeleteAreYouSure: Are you sure you want to delete?
ConfirmPlease: Please confirm
Actions: Actions
Homepage: Home page
MenuButton: Menu button
Save: Save
Cancel: Cancel
Dele: Delete
Change: Change
Add: Add
NoData: No data
NothingToShow: Nothing to show
EmptyDataSet: Empty dataset
AccessDeniedAdminsOnly: Only administrators have access to this page. Please log in with an administrator account
LoginPlease: Please log in to access this page
Users: Users
Email: E-mail
ResetPassword: Reset password
RestoreLogin: Restore login
Password: Password
Username: Username
SignOut: Sign out
SignIn: Sign in
Home: Home
AppName: EventQr

Doc001 appname@Text href@Text: The web application <a class="link" href=#{href} target=_blank>#{appname}</a> registers users for events.
Doc002 href@Text: <a class="link" href=#{href} target=_blank>Project repository</a> on GitHub.
Doc003 href@Text: Please note that the application currently running is a demo application. Any actions are allowed and encouraged. <a class="link" href=#{href} target=_blank>Report issues</a> on GitHub.
Doc005: Integration with external APIs