IssueTracking: Отслеживание ошибок
GeolocationAlternativesMessageCoordinates: координаты
GeolocationAlternativesMessageOrThe: или
GeolocationAlternativesMessageAddress: адрес
GeolocationAlternativesMessageSuffix: вашего местоположения
GeolocationAlternativesMessagePrefix: Либо вы можете указать
GeolocationStatusTimeoutUserMessage: Время ожидания определения вашего местоположения истекло.
GeolocationStatusUserMessage: Ваше местоположение определяется с помощью возможностей геолокации браузера.
GeolocationNotSupportedUserMessage: Похоже, ваш браузер не поддерживает геолокацию.
GeolocationStatusDisabledExploreNearby: Похоже, у вас отключена геолокация, так как она нужна для исследования близлежащих объектов. Включите геолокацию для этого сайта в настройках браузера.
GeolocationStatusDisabledUserMessage: Похоже, у вас отключена геолокация, так как она необходима для определения вашего местоположения. Включите геолокацию для этого сайта в настройках браузера.
AboutYourLocation: О вашем местоположении
GeolocationOptions: Параметры геолокации
Geolocation: Геолокация
Latitude: Широта
Longitude: Долгота
GeolocationDisabled: Геолокация отключена
Timeout: Тайм-аут
PositionUnavailable: Местоположение недоступно
Find: Найти
PublicInstitutions: Общественные учреждения
Parks: Парки
Nearby: Поблизости
InKilometers: в километрах
NearbyRadius: Радиус вблизи моего местоположения
Radius: Радиус
MainMenu: Главное меню
RestaurantsShopsAndMore: Рестораны, магазины и многое другое
Attractions: Достопримечательности
MapStyleOptions: Варианты стиля карты
Compass: Компас
MyLocation: Мое местоположение
ZoomOut: Уменьшить масштаб
ZoomIn: Увеличить масштаб
ExploreNearby: Исследуйте поблизости
NoShops: Магазинов нет
NoShopsWereFoundForSearchTerms: Не найдено ни одного магазина, соответствующего всем условиям поиска
NoRestaurants: Ресторанов нет
NoRestaurantsWereFoundForSearchTerms: Не найдено ни одного ресторана, соответствующего всем условиям поиска
ThatIsAll: Вот и всё
LoadMore: Показать ещё
Type: Тип
Brand: Бренд
ShowOnMap: Показать на карте
Phone: Телефон
OpeningHours: Часы работы
Address: Адрес
Cuisine: Кухня
Restaurant: Ресторан
SearchForShops: Поиск магазинов
SearchForRestaurants: Поиск ресторанов
SearchByNameOrAddress: Поиск по названию или адресу
SearchPlacesByNameOrAddress: Поиск мест по названию или адресу
SearchPlacesByName: Поиск мест по названию
SearchByStreetNamesAndPoi: Поиск по названиям улиц и интересующих мест
NoLocationsWereFound: Не найдено ни одного местоположения, соответствующего вашему запросу
Shops: Магазины
Restaurants: Рестораны
Search: Поиск
StyleNavigationNight: Ночь навигация
StyleNavigationDay: Навигация день
StyleSatelliteStreets: Улицы-спутник
StyleSatellite: Спутник
StyleDark: Темный
StyleLight: Светлый
StyleOutdoors: На улице
StyleStreets: Улицы
CouldNotGetPosition: Не удалось получить позицию
Landmark: Достопримечательность
Close: Закрыть
Tooltip: Подсказка
Duration: Продолжительность
EndDate: Дата окончания
StartDate: Дата начала
Chart: Диаграмма
Action: Действие
Timestamp: Временная метка
Hours: Часы
DurationHours: Продолжительность
Remarks: Замечания
StateMachineDiagram: Схема машины состояний
BasicEntities: Базовые сущности
NotAuthorized: Не разрешено
LoginToAccessPlease: Пожалуйста, войдите в систему, чтобы получить доступ к этой странице
Statistics: Статистика
Owner: Владелец
Sequence: Последовательность
End: Конец
Start: Начало
LoginForMoreDetailsPlease: Пожалуйста, войдите в систему для более подробной информации
WelcomeTo: Добро пожаловать на
Location: Локация
ChangePassword: Изменить пароль
AlreadyExists: Уже существует
No: Нет
Yes: Да
DemoUserAccounts: Демо-аккаунты
User: Пользователь
Administrator: Администратор
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
Authentication: Аутентификация
Or: или
Back: Вернуться
BackToHomepage: Вернуться на домашнюю страницу
InvalidArguments: Неверные аргументы
PermissionDenied: Доступ запрещен
PageNotFound: Страница не найдена
PleaseAddIfNecessary: Пожалуйста, добавьте, если необходимо
Empty: Пустой
Copy: Копировать
Settings: Настройки
Country: Страна
CountryRU: Россия
CountryUS: США
Language: Язык
LangRu: Русский
LangEn: Английский
Create: Создать
Link: Ссылка
Attribution: Атрибуция
Logo: Логотип
Photo: Фото
Url: URL-адрес
Details: Подробности
Title: Название
RecordDeleted: Запись удалена
InvalidFormData: Неверные данные формы
DateCreated: Дата создания
TimeCreated: Время создания
Author: Автор
SourceCode: Исходный код
GitHub: GitHub
EntityRelationshipDiagram: Диаграмма взаимосвязи сущностей
Documentation: Документация
Description: Описание
Name: Имя
RecordEdited: Запись отредактирована
RecordAdded: Запись добавлена
Edit: Редактировать
DeleteAreYouSure: Вы уверены, что хотите удалить?
ConfirmPlease: Пожалуйста подтвердите
Actions: Действия
Homepage: Домашняя страница
MenuButton: Кнопка меню
Save: Сохранить
Cancel: Отмена
Dele: Удалить
Change: Изменить
Add: Добавить
NoData: Нет данных
NothingToShow: Нечего показывать
EmptyDataSet: Пустой набор данных
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите для доступа к этой странице
Users: Пользователи
Email: E-mail
ResetPassword: Сбросить пароль
RestoreLogin: Восстановить вход
Password: Пароль
Username: Логин
SignOut: Выйти
SignIn: Войти
Home: Главная
AppName: EventQr

Doc001 appname href: Веб-приложение <a class="link" href=#{href} target=_blank>#{appname}</a> регистрирует пользователей на события.
Doc002 href: <a class="link" href=#{href} target=_blank>Репозиторий проекта</a> на GitHub.
Doc003 href: Обратите внимание, что приложение, работающее в данный момент, является демонстрационным. Любые действия разрешены и поощряются. <a class="link" href=#{href} target=_blank>Сообщайте об ошибках</a> на GitHub.
Doc005: Интеграция с внешними API