PasswordRecovery: Восстановление пароля
CreatePassword: Создание пароля
EmailVerification: Проверка электронной почты
VerifyEmailPlease: Пожалуйста, подтвердите вашу электронную почту
JustSentEmailTo: Мы только что отправили электронное письмо на
ClickToVerifyAccount: Нажмите ссылку в письме, чтобы подтвердить свою учетную запись
DidNotGetEmail: Не получили письмо?
ResendEmail: Отправить письмо повторно
ForgotYourPassword: Забыли пароль?
DoNotHaveAnAccount: У вас нет учетной записи?
CreateAccount: Зарегистрироваться
GmailAccountNotSet: Аккаунт Gmail не установлен. Инициализируйте токены.
ThankYou: Спасибо
ConfirmEmailPlease: Пожалуйста, подтвердите свой адрес электронной почты, нажав на ссылку ниже
VerifyYourEmailAddress: Проверьте свой адрес электронной почты
SignInWithGoogle: Войти через Google
EventAndParticipantManagement: Управление мероприятиями и участниками
YouDoNotHaveEventsToAttendYet: У вас пока нет запланированных мероприятий для посещения
Schedule: Расписание
Upcoming: Предстоящие
MyVisitingSchedule: Мой график посещений
All: Все
MyEvents: Мои мероприятия
AllEvents: Все мероприятия
Theme: Тема
UserAccount: Учетная запись пользователя
Profile: Профиль
SuperuserCannotBeDeleted: Суперпользователя нельзя удалить
NotManagerOfEventSorry: К сожалению, вы не являетесь менеджером этого мероприятия. Вы не можете регистрировать пользователей на мероприятия, которыми вы не управляете.
NotYourQrCodeSorry: К сожалению, это не ваш QR-код. Вы отсканировали неправильный QR-код.
DataAdministrator: Администратор данных
EventManager: Менеджер мероприятий
UserRoles: Роли пользователей
AccessDeniedManagerOrAdminOnly: Доступ к этой странице имеют только менеджеры мероприятий и администраторы данных. Пожалуйста, войдите в систему как менеджер событий или администратор данных
Manager: Менеджер
FillInCard: Заполнить карточку
CardDoesNotContainAdditionalInfo: Карточка не содержит дополнительных данных для отображения
NumberSign: №
LoginToSeeYourCardsPlease: Пожалуйста, войдите в систему, чтобы увидеть свои карточки
YouDoNonHaveCardsYet: У вас пока нет карточек
MyCards: Мои карточки
RegisterForEvent: Записаться на мероприятие
SelectCardToRegister: Выберите карту для регистрации
YouDoNotHaveACardToRegisterYet: У вас пока нет карты для регистрации на мероприятие
YouAreRegisteredForThisEvent: Вы зарегистрированы на это мероприятие
RegisterWithQrCode: Записаться с QR-кодом
RegisterForThisEvent: Записаться на это мероприятие
EventStartTime: Время начала мероприятия
YourOtherSubscriptions: Ваши другие подписки
UnsubscribeAreYouSure: Вы уверены, что хотите отписаться?
Unsubscribe: Отписаться
UnknownDevice: Неизвестное устройство
AllSubscriptions: Все подписки
VapidCanBeGeneratedByAdmin: Ключ VAPID может быть сгенерирован администратором
VapidRequiredToPushNotifications: Для отправки push-уведомлений требуется действительный ключ VAPID
Notification: Уведомление
New: Новое
From: От
Sent: Отправлено
Unread: Непрочитано
Read: Прочитано
MessageSent: Сообщение отправлено
Publisher: Публикатор
NoNotificationsForYouAtTheMoment: На данный момент для вас нет уведомлений
Notifications: Уведомления
ProvideRecipientEmailPlease: Пожалуйста, укажите адрес электронной почты получателя
CheckAtLeastOneOptionPlease: Пожалуйста, отметьте хотя бы один из вариантов
UserSessionLocalTesting: Пользовательская сессия (локальное тестирование)
ProjectId: Идентификатор проекта
ClientSecret: Секрет клиента
ClientId: Идентификатор клиента
Superuser: Суперпользователь
SelectLocationToStoreRefreshToken: Выберите место для хранения токена обновления
UserAccountThroughWhichMailWillBeSent: Учетная запись пользователя, через которую будет отправляться почта
UnknownMessageRecipient: Неизвестный получатель сообщения
UnknownMessagePublisher: Неизвестный издатель сообщения
UnknownAccountForSendingEmail: Неизвестная учетная запись для отправки электронной почты
RefreshTokenIsNotInitialized: Токен обновления не инициализирован
UnableToObtainAccessToken: Не удалось получить токен доступа
Vapid: VAPID
Gmail: Gmail
InvalidGoogleAPITokens: Неверные токены Google API
VapidGenerationWarning: Генерация нового ключа VAPID потребует от всех клиентов повторной подписки на push-уведомления
Generate: Генерировать
GoogleSecretManager: Google Secret Manager
GmailAccount: Учетная запись Gmail
Cleared: Очищено
ClearSettings: Сбросить
InvalidStoreType: Неверный тип хранилища
StoreType: Тип хранилища
Database: База данных
UserSession: Пользовательская сессия
Initialize: Инициализировать
Tokens: Токены
NotificationSent: Уведомление отправлено
UploadPoster: Загрузить постер
Poster: Плакат
Overview: Обзор
UseCaseDiagram: Диаграмма вариантов использования
ReadMessage: Прочитать
DismissNotification: Закрыть
EnableCameraPlease: Пожалуйста, включите камеру в настройках вашего браузера
CameraWasTurnedOff: Похоже, камера была выключена
EnableNotificationsPlease: Пожалуйста, включите уведомления в настройках вашего браузера
NotificationsHaveBeenDisabled: Похоже, уведомления отключены
UnsubscribeSuccessful: Отписка прошла успешно
SubscriptionSuccessful: Подписка прошла успешно
VapidNotInitializedProperly: VAPID не был инициализирован должным образом
SubscribeToPushNotifications: Подписаться на push-уведомления
AnotherAccountAccessProhibited: Доступ к учетной записи другого пользователя запрещен
ItLooksLikeUserNotSubscribedToPushNotifications: Похоже, пользователь не подписан на push-уведомления
ItLooksLikeUserNotSubscribed: Похоже, пользователь не подписан
SendPushNotification: Отправить push-уведомление
NotificationSentToSubscribersN n: Уведомление отправлено #{show n} подписчикам
EmailAddress: Адрес электронной почты
Message: Сообщение
MessageSubject: Тема
Header: Заголовок
SendEmail: Отправить электронное письмо
NotificationToAttendee: Оповещение участнику
SendNotification: Отправить оповещение
Send: Отправить
ShowUserQrCode: Показать QR-код пользователя
NotifyUser: Уведомить пользователя
NotifyUserAboutUpcomingEvent: Уведомить пользователя о предстоящем событии 
NoEventsFound: Мероприятий не найдено
NumberOfAttendees: Количество участников
UserHasNoCardsYet: У пользователя пока нет карточек
NoFieldsForThisCardYet: Для этой карточки пока нет полей
NewFieldNameRequired: Необходимо указать имя нового поля
Value: Значение
Cardholder: Владелец карты
CardNumber: Номер карты
NewField: Новое поле
AddField: Добавить поле
TotalAttendees: Всего участников
TotalEventsForThisMonth: Всего событий за этот месяц
NoEventsYet: Мероприятий пока нет
NoAttendeesForThisEventYet: Участников на это мероприятие пока нет
List: Список
RegistrationDate: Дата регистрации
IssueDate: Дата выпуска
NoCardsRegisteredYet: Пока что ни одна карта не зарегистрирована
EventsCatalogue: Каталог событий
SearchEvents: Поиск мероприятий
SelectAnEventToRegisterPlease: Пожалуйста, выберите мероприятие для регистрации
NoUpcomingEventsYet: Предстоящих событий пока нет
TotalEventsForThisMonthN n: Всего событий за этот месяц: #{show n}
NoEventsForThisMonth: В данный момент событий на этот месяц нет
QrCode: QR-код
Attendee: Участник
Attendees: Участники
Subscribers: Подписчики
UserSuccessfullyRegisteredForEvent: Пользователь успешно зарегистрирован на мероприятие
ScanAgain: Сканировать повторно
ConfirmUserRegistrationForEventPlease: Пожалуйста, подтвердите регистрацию пользователя на мероприятие
Registration: Регистрация
NoEventsForThisDayYet: На этот день пока нет мероприятий
Register: Зарегистрировать
RegisterUserForEvent: Зарегистрировать пользователя на мероприятие
RegistrationConfirmation: Подтверждение регистрации
RegistrationForEvent: Регистрация на мероприятие
Scan: Сканировать
Card: Карточка
Cards: Карточки
UserCard: Карточка пользователя
UserCards: Карточки пользователей
PersonalUserCard: Персональная карта пользователя
PersonalUserCards: Персональные карты пользователя
UpcomingEvents: Предстоящие события
ScanQrCode: Сканировать QR-код
ScanQrCodeAndLinkToEvent: Сканировать QR-код посетителя и связать его с мероприятием
ScanQrCodeAndLinkToThisEvent: Сканировать QR-код посетителя и связать его с этим мероприятием
EventsCalendar: Календарь событий
Time: Время
Events: События
Event: Событие
Next: Следующий
Previous: Предыдущий
Sun: вс
Sat: сб
Fri: пт
Thu: чт
Wed: ср
Tue: вт
Mon: пн
Calendar: Календарь
Stop: Остановить
PointYourCameraToScan: Наведите камеру на QR-код для сканирования
Scanner: Сканер

IssueTracking: Отслеживание ошибок
Timeout: Тайм-аут
Find: Найти
Radius: Радиус
MainMenu: Главное меню
Type: Тип
Brand: Бренд
Phone: Телефон
OpeningHours: Часы работы
Address: Адрес
Search: Поиск
Landmark: Достопримечательность
Close: Закрыть
Tooltip: Подсказка
Duration: Продолжительность
EndDate: Дата окончания
StartDate: Дата начала
Chart: Диаграмма
Action: Действие
Timestamp: Временная метка
Hours: Часы
DurationHours: Продолжительность
Remarks: Замечания
StateMachineDiagram: Схема машины состояний
BasicEntities: Базовые сущности
NotAuthorized: Не разрешено
SignInToAccessPlease: Пожалуйста, войдите в систему, чтобы получить доступ к этой странице
LoginToAccessPlease: Пожалуйста, войдите в систему, чтобы получить доступ к этой странице
Statistics: Статистика
Owner: Владелец
Sequence: Последовательность
End: Конец
Start: Начало
LoginForMoreDetailsPlease: Пожалуйста, войдите в систему для более подробной информации
WelcomeTo: Добро пожаловать на
Location: Локация
ChangePassword: Изменить пароль
AlreadyExists: Уже существует
No: Нет
Yes: Да
DemoUserAccounts: Демо-аккаунты
User: Пользователь
Administrator: Администратор
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
Authentication: Аутентификация
Or: или
Back: Вернуться
BackToHomepage: Вернуться на домашнюю страницу
InvalidArguments: Неверные аргументы
PermissionDenied: Доступ запрещен
PageNotFound: Страница не найдена
PleaseAddIfNecessary: Пожалуйста, добавьте, если необходимо
Empty: Пустой
Copy: Копировать
Settings: Настройки
Country: Страна
CountryRU: Россия
CountryUS: США
Language: Язык
LangRu: Русский
LangEn: Английский
Create: Создать
Link: Ссылка
Attribution: Атрибуция
Logo: Логотип
Photo: Фото
Url: URL-адрес
Details: Подробности
Title: Название
RecordDeleted: Запись удалена
InvalidFormData: Неверные данные формы
DateCreated: Дата создания
TimeCreated: Время создания
Author: Автор
SourceCode: Исходный код
GitHub: GitHub
EntityRelationshipDiagram: Диаграмма взаимосвязи сущностей
Documentation: Документация
Description: Описание
Name: Имя
RecordEdited: Запись отредактирована
RecordAdded: Запись добавлена
Edit: Редактировать
DeleteAreYouSure: Вы уверены, что хотите удалить?
ConfirmPlease: Пожалуйста подтвердите
Actions: Действия
Homepage: Домашняя страница
MenuButton: Кнопка меню
Save: Сохранить
Cancel: Отмена
Dele: Удалить
Change: Изменить
Add: Добавить
NoData: Нет данных
NothingToShow: Нечего показывать
EmptyDataSet: Пустой набор данных
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите в систему
Users: Пользователи
Email: Электронная почта
ResetPassword: Сбросить пароль
RestoreLogin: Восстановить вход
Password: Пароль
Username: Логин
SignOut: Выйти
SignIn: Войти
Home: Главная
MetaDescription: Управление мероприятиями и посещаемостью
AppName: EventQr

Doc000: Управление мероприятиями и посещаемостью
Doc001 appname href: <a class="link" href=#{href} target=_blank>#{appname}</a> позволяет менеджерам регистрировать мероприятия, уведомлять пользователей о предстоящих мероприятиях и отслеживать посещаемость.
Doc002 href: <a class="link" href=#{href} target=_blank>Репозиторий проекта</a> на GitHub.
Doc003 href: Обратите внимание, что приложение, работающее в данный момент, является демонстрационным. Любые действия разрешены и поощряются. <a class="link" href=#{href} target=_blank>Сообщайте об ошибках</a> на GitHub.
Doc004: Учетная запись суперпользователя определяется во время развертывания. Суперпользователь управляет другими пользователями и предоставляет или отзывает права администратора конкретным пользователям.
Doc005: Интеграция с внешними API
Doc006: Менеджер мероприятий может создавать мероприятия, отправлять уведомления, назначать участников только на те мероприятия, которыми он управляет.
Doc007: Администраторы данных имеют полный доступ ко всем событиям и данным.