NumberOfAttendees: Количество участников
UserHasNoCardsYet: У пользователя пока нет карточек
NoFieldsForThisCardYet: Для этой карточки пока нет полей
NewFieldNameRequired: Необходимо указать имя нового поля
Value: Значение
Cardholder: Владелец карты
CardNumber: Номер карты
NewField: Новое поле
AddField: Добавить поле
TotalAttendees: Всего участников
TotalEventsForThisMonth: Всего событий за этот месяц
NoEventsYet: Мероприятий пока нет
NoAttendeesForThisEventYet: Участников на это мероприятие пока нет
List: Список
RegistrationDate: Дата регистрации
IssueDate: Дата выпуска
NoCardsRegisteredYet: Пока что ни одна карта не зарегистрирована
EventsCatalogue: Каталог событий
SearchEvents: Поиск мероприятий
SelectAnEventToRegisterPlease: Пожалуйста, выберите мероприятие для регистрации
NoUpcomingEventsYet: Предстоящих событий пока нет
TotalEventsForThisMonthN n: Всего событий за этот месяц: #{show n}
NoEventsForThisMonth: В данный момент событий на этот месяц нет
QrCode: QR-код
Attendee: Участник
Attendees: Участники
Subscribers: Подписчики
UserSuccessfullyRegisteredForEvent: Пользователь успешно зарегистрирован на мероприятие
ScanAgain: Сканировать повторно
ConfirmUserRegistrationForEventPlease: Пожалуйста, подтвердите регистрацию пользователя на мероприятие
Registration: Регистрация
NoEventsForThisDayYet: На этот день пока нет мероприятий
Register: Зарегистрировать
RegisterUserForEvent: Зарегистрировать пользователя на мероприятие
RegistrationConfirmation: Подтверждение регистрации
RegistrationForEvent: Регистрация на мероприятие
Scan: Сканировать
Card: Карточка
Cards: Карточки
UserCard: Карточка пользователя
UserCards: Карточки пользователей
PersonalUserCard: Персональная карта пользователя
PersonalUserCards: Персональные карты пользователя
UpcomingEvents: Предстоящие события
ScanQrCode: Сканировать QR-код
ScanQrCodeAndLinkToEvent: Сканировать QR-код посетителя и связать его с мероприятием
EventsCalendar: Календарь событий
Time: Время
Events: События
Event: Событие
Next: Следующий
Previous: Предыдущий
Sun: вс
Sat: сб
Fri: пт
Thu: чт
Wed: ср
Tue: вт
Mon: пн
Calendar: Календарь
Stop: Остановить
PointYourCameraToScan: Наведите камеру на QR-код для сканирования
Scanner: Сканер

IssueTracking: Отслеживание ошибок
Timeout: Тайм-аут
Find: Найти
Radius: Радиус
MainMenu: Главное меню
Type: Тип
Brand: Бренд
Phone: Телефон
OpeningHours: Часы работы
Address: Адрес
Search: Поиск
Landmark: Достопримечательность
Close: Закрыть
Tooltip: Подсказка
Duration: Продолжительность
EndDate: Дата окончания
StartDate: Дата начала
Chart: Диаграмма
Action: Действие
Timestamp: Временная метка
Hours: Часы
DurationHours: Продолжительность
Remarks: Замечания
StateMachineDiagram: Схема машины состояний
BasicEntities: Базовые сущности
NotAuthorized: Не разрешено
LoginToAccessPlease: Пожалуйста, войдите в систему, чтобы получить доступ к этой странице
Statistics: Статистика
Owner: Владелец
Sequence: Последовательность
End: Конец
Start: Начало
LoginForMoreDetailsPlease: Пожалуйста, войдите в систему для более подробной информации
WelcomeTo: Добро пожаловать на
Location: Локация
ChangePassword: Изменить пароль
AlreadyExists: Уже существует
No: Нет
Yes: Да
DemoUserAccounts: Демо-аккаунты
User: Пользователь
Administrator: Администратор
InvalidUrlOrRemoved: Неверный URL-адрес или ресурс удален
Authentication: Аутентификация
Or: или
Back: Вернуться
BackToHomepage: Вернуться на домашнюю страницу
InvalidArguments: Неверные аргументы
PermissionDenied: Доступ запрещен
PageNotFound: Страница не найдена
PleaseAddIfNecessary: Пожалуйста, добавьте, если необходимо
Empty: Пустой
Copy: Копировать
Settings: Настройки
Country: Страна
CountryRU: Россия
CountryUS: США
Language: Язык
LangRu: Русский
LangEn: Английский
Create: Создать
Link: Ссылка
Attribution: Атрибуция
Logo: Логотип
Photo: Фото
Url: URL-адрес
Details: Подробности
Title: Название
RecordDeleted: Запись удалена
InvalidFormData: Неверные данные формы
DateCreated: Дата создания
TimeCreated: Время создания
Author: Автор
SourceCode: Исходный код
GitHub: GitHub
EntityRelationshipDiagram: Диаграмма взаимосвязи сущностей
Documentation: Документация
Description: Описание
Name: Имя
RecordEdited: Запись отредактирована
RecordAdded: Запись добавлена
Edit: Редактировать
DeleteAreYouSure: Вы уверены, что хотите удалить?
ConfirmPlease: Пожалуйста подтвердите
Actions: Действия
Homepage: Домашняя страница
MenuButton: Кнопка меню
Save: Сохранить
Cancel: Отмена
Dele: Удалить
Change: Изменить
Add: Добавить
NoData: Нет данных
NothingToShow: Нечего показывать
EmptyDataSet: Пустой набор данных
AccessDeniedAdminsOnly: Доступ к этой странице имеют только администраторы. Пожалуйста, войдите под учетной записью администратора
LoginPlease: Пожалуйста, войдите для доступа к этой странице
Users: Пользователи
Email: Электронная почта
ResetPassword: Сбросить пароль
RestoreLogin: Восстановить вход
Password: Пароль
Username: Логин
SignOut: Выйти
SignIn: Войти
Home: Главная
AppName: EventQr

Doc001 appname href: Веб-приложение <a class="link" href=#{href} target=_blank>#{appname}</a> регистрирует пользователей на события.
Doc002 href: <a class="link" href=#{href} target=_blank>Репозиторий проекта</a> на GitHub.
Doc003 href: Обратите внимание, что приложение, работающее в данный момент, является демонстрационным. Любые действия разрешены и поощряются. <a class="link" href=#{href} target=_blank>Сообщайте об ошибках</a> на GitHub.
Doc005: Интеграция с внешними API